version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com/dvag
    token: ${{secrets.PACKAGES_PAT}}
updates:
  - package-ecosystem: npm
    directory: /frontend/
    registries:
      - npm-github
    schedule:
      interval: daily
