# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ase-itcs-frontend-ent-01

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.PACKAGES_PAT}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/dvag
          scope: '@dvag'

      - name: npm install, build, and test
        working-directory: frontend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_PAT }}
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: itcs-frontend
          path: ./frontend/dist/itcs-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: itcs-frontend

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'ase-itcs-frontend-ent-01'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B3E706680A6447AF9182851BFDD6D92C }}
          package: .
